{% set name = "piff" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rmjarvis/Piff/archive/v{{ version }}.tar.gz
  sha256: 61f917273ae07ac62a975dc6be51659f9128c6c10fd97aaadb144a5e589512db

build:
  skip: true  # [win]
  number: 0
  # uses scripts so cannot be noarch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - setuptools
    - pybind11 >=2.2
    - eigen >=3.3
    - numpy
    - llvm-openmp  # [osx]
  run:
    - python
    - numpy
    - scipy
    - pyyaml
    - treecorr >=4.0
    - fitsio >=1
    - matplotlib-base >=3.3.0
    - lsstdesc.coord >=1.0.5
    - galsim >=2.3
    - treegp >=0.6

test:
  # requires:
  #   - pip
  imports:
    - piff
  commands:
    - piffify --help
    - plotify --help
    - meanify --help
    # - pip check

about:
  home: https://github.com/rmjarvis/Piff
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PSFs In the Full FOV
  doc_url: http://rmjarvis.github.io/Piff/html

extra:
  recipe-maintainers:
    - beckermr
    - rmjarvis
